// ── Algorithms ────────────────────────────────────────────────────────────────

export type KdfAlgorithm = 'argon2id_hkdf' | 'hkdf';
// 'hkdf' is obsolete — not generated by the Phase 3+ client.
// Retained for reading any existing entries in the database.

// ── KDF parameters ────────────────────────────────────────────────────────────

export interface Argon2idHkdfParams {
  argon2Salt:        string;                                   // base64, 32 bytes
  argon2Memory:      number;                                   // 4096 (auto) | 65536 (manual)
  argon2Iterations:  number;                                   // 1 (auto) | 3 (manual)
  argon2Parallelism: number;                                   // 1 (auto) | 4 (manual)
  argon2KeyLength:   32;
  hkdfSalt:          string;                                   // base64, 32 bytes, distinct from argon2Salt
  hkdfInfo:          'skychat-backup-v1' | 'skychat-backup-key-v1';
  hashAlgorithm:     'sha256';
  keyLength:         32;
}

// Retained for reading legacy entries only — not generated in Phase 3+
export interface HkdfParams {
  hkdfSalt:      string;
  hkdfInfo:      string;
  hashAlgorithm: 'sha256';
  keyLength:     32;
}

export type KdfParams = Argon2idHkdfParams | HkdfParams;

// ── Server responses ──────────────────────────────────────────────────────────

export interface BackupSettings {
  enabled:           boolean;
  currentKeyVersion: number | null;
  enabledAt:         number | null;
  lastBackupAt:      number | null;
}

export interface BackupKeyVersionResponse {
  id:            string;
  userDid:       string;
  versionNumber: number;
  kdfAlgorithm:  KdfAlgorithm;
  kdfParams:     KdfParams;
  createdAt:     number;
  supersededAt:  number | null;
}

// ── Encrypted payload ─────────────────────────────────────────────────────────

export interface EncryptedBackupPayload {
  encryptionVersion: number;    // 1 in Phase 3
  cacheVersion:      number;    // 1 in Phase 3
  iv:                string;    // base64, 12 random bytes
  data:              string;    // base64: AES-GCM-256(backupKey, JSON(BackupPayload))
}

// ── Plaintext payload types (discriminated union) ─────────────────────────────
// These describe what is placed INSIDE the encrypted payload — never transmitted
// to the server in plaintext.

export interface BackupMessagePlaintext {
  schemaVersion:  1;
  type:           'message';
  plaintext:      string;
  conversationId: string;
  messageId:      string;
  createdAt:      number;
  senderDid?:     string;
}

export interface BackupGroupStatePlaintext {
  schemaVersion:  1;
  type:           'group-state';
  conversationId: string;
  groupState:     string;   // base64-encoded MLS group state
}

export type BackupPayload = BackupMessagePlaintext | BackupGroupStatePlaintext;

// ── Progress ──────────────────────────────────────────────────────────────────

export interface BackfillProgress {
  total:    number;    // estimated — may be imprecise
  uploaded: number;
  done:     boolean;
}

export interface RestoreProgress {
  downloaded: number;
  restored:   number;
  done:       boolean;
  error?:     string;
}

export interface RebuildProgress {
  phase:    'deleting' | 'uploading' | 'done';
  uploaded: number;
  total:    number;
  done:     boolean;
  error?:   string;
}

// ── Input to the backend API ──────────────────────────────────────────────────

export interface BackupMessageInput {
  conversationId:    string;
  messageId:         string;
  encryptedPayload:  EncryptedBackupPayload;
  encryptionVersion: number;
  cacheVersion:      number;
  keyVersion:        number;
  createdAt:         number;
  entryType?:        'message' | 'group-state';
}

// ── Restore result ────────────────────────────────────────────────────────────

export interface RestoreResult {
  restoredMessages:    number;
  restoredGroupStates: Record<string, string>;
}
